[tools]
dotnet = "10.0.301"
eza = "0.23.4"
fzf = "0.73.1"
gh = "2.93.0"
herdr = "0.6.8"
jq = "1.8.1"
neovim = "0.12.2"
node = "26.3.0"
"npm:npm" = "11.16.0"
"npm:@anthropic-ai/claude-code" = { version = "2.1.170", npm_args = "--ignore-scripts=false" }
"npm:@openai/codex" = "0.138.0"
"npm:opencode-ai" = { version = "1.16.2", npm_args = "--ignore-scripts=false" }
powershell = "7.6.2"
rg = "15.1.0"
zoxide = "0.9.9"
