[tools]
dotnet = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
herdr = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:npm" = "latest"
"npm:opencode-ai" = "latest"
powershell = "latest"
zoxide = "latest"
