set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g status-bg "#1e1e2e"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind-key x kill-pane
bind-key & kill-window

bind-key T display-popup -E "sesh connect \"$(sesh list -tc | fzf)\""

run '~/.tmux/plugins/tpm/tpm'
